apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-config
data:
  init.sql: |
    ALTER USER postgres PASSWORD '123';
    CREATE TABLE veiculos(marca VARCHAR(50), modelo VARCHAR(50), ano VARCHAR(50), cor VARCHAR(50), preco REAL, flagvendido VARCHAR(1), id SERIAL);